### ISSUE TITLE
Centrosymmetry

### ISSUE THREAD

**Issue by pjgaudre** [pjgaudre/DESincEig.jl#7]
I can't seem to get my code for centrosymmetry to work. When I run my code, I obtain the following error:

using DESincEig, SincFun
(RESULTS, All_Abs_Error_Approx , hoptimal , n, MatrixSizes)=SincEigen(x->x.^2+x.^4,ones,infinite2{Float64}(), [0.125,0.125] , [2.0,2.0] , pi/4,Centro=true)

WARNING: [a,b] concatenation is deprecated; use [a;b] instead
 in depwarn at deprecated.jl:73
 in oldstyle_vcat_warning at abstractarray.jl:29
 in vect at abstractarray.jl:38
 in SincEigen at C:\Users\Philippe.julia\v0.4\DESincEig\src\DESincEig.jl:228
while loading no file, in expression starting on line 0
ERROR: MethodError: `call` has no method matching call(::Float64, ::Array{Float6
4,1})
Closest candidates are:
  BoundsError()
  BoundsError(::Any...)
  DivideError()
  ...
 in qtilde at C:\Users\Philippe.julia\v0.4\DESincEig\src\DESincEig.jl:158
 in SincEigen at C:\Users\Philippe.julia\v0.4\DESincEig\src\DESincEig.jl:222

It appears to be in the function qtilde, however, when I run my code without any centrosymmety, (Centro =false), there is no problem....

**Comment by MikaelSlevinsky** [comment]
It looks like you've redefined the input function q to be a Float64.

Cheers,

Mikael

**Comment by pjgaudre** [comment]
I used the variable q as my center element in one of the centrosymmetric matrices. Fixed the issue, by switching the name of the variable from q to qc.
